/**
 * Perplexity AI Chat Completions API
 * API for generating a model\'s response for the given chat conversation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChatCompletionsPostRequestMessagesInner } from '../models/ChatCompletionsPostRequestMessagesInner';
import { HttpFile } from '../http/http';

export class ChatCompletionsPostRequest {
    'model': ChatCompletionsPostRequestModelEnum;
    'messages': Array<ChatCompletionsPostRequestMessagesInner>;
    'maxTokens'?: number;
    'temperature'?: number;
    'topP'?: number;
    'topK'?: number;
    'stream'?: boolean;
    'presencePenalty'?: number;
    'frequencyPenalty'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "model",
            "baseName": "model",
            "type": "ChatCompletionsPostRequestModelEnum",
            "format": ""
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<ChatCompletionsPostRequestMessagesInner>",
            "format": ""
        },
        {
            "name": "maxTokens",
            "baseName": "max_tokens",
            "type": "number",
            "format": ""
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "number",
            "format": ""
        },
        {
            "name": "topP",
            "baseName": "top_p",
            "type": "number",
            "format": ""
        },
        {
            "name": "topK",
            "baseName": "top_k",
            "type": "number",
            "format": ""
        },
        {
            "name": "stream",
            "baseName": "stream",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "presencePenalty",
            "baseName": "presence_penalty",
            "type": "number",
            "format": ""
        },
        {
            "name": "frequencyPenalty",
            "baseName": "frequency_penalty",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChatCompletionsPostRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ChatCompletionsPostRequestModelEnum {
    Pplx7bChat = 'pplx-7b-chat',
    Pplx70bChat = 'pplx-70b-chat',
    Pplx7bOnline = 'pplx-7b-online',
    Pplx70bOnline = 'pplx-70b-online',
    Llama270bChat = 'llama-2-70b-chat',
    Codellama34bInstruct = 'codellama-34b-instruct',
    Codellama70bInstruct = 'codellama-70b-instruct',
    Mistral7bInstruct = 'mistral-7b-instruct',
    Mixtral8x7bInstruct = 'mixtral-8x7b-instruct'
}

