/**
 * Perplexity AI Chat Completions API
 * API for generating a model\'s response for the given chat conversation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChatCompletionResponseChoicesInner } from '../models/ChatCompletionResponseChoicesInner';
import { ChatCompletionResponseUsage } from '../models/ChatCompletionResponseUsage';
import { HttpFile } from '../http/http';

export class ChatCompletionResponse {
    'id'?: string;
    'model'?: string;
    'object'?: ChatCompletionResponseObjectEnum;
    'created'?: number;
    'choices'?: Array<ChatCompletionResponseChoicesInner>;
    'usage'?: ChatCompletionResponseUsage;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "ChatCompletionResponseObjectEnum",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number",
            "format": ""
        },
        {
            "name": "choices",
            "baseName": "choices",
            "type": "Array<ChatCompletionResponseChoicesInner>",
            "format": ""
        },
        {
            "name": "usage",
            "baseName": "usage",
            "type": "ChatCompletionResponseUsage",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChatCompletionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ChatCompletionResponseObjectEnum {
    ChatCompletion = 'chat.completion'
}

