/**
 * Perplexity AI Chat Completions API
 * API for generating a model\'s response for the given chat conversation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChatCompletionResponseChoicesInnerDelta } from '../models/ChatCompletionResponseChoicesInnerDelta';
import { ChatCompletionsPostRequestMessagesInner } from '../models/ChatCompletionsPostRequestMessagesInner';
import { HttpFile } from '../http/http';

export class ChatCompletionResponseChoicesInner {
    'index'?: number;
    'finishReason'?: ChatCompletionResponseChoicesInnerFinishReasonEnum;
    'message'?: ChatCompletionsPostRequestMessagesInner;
    'delta'?: ChatCompletionResponseChoicesInnerDelta;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": ""
        },
        {
            "name": "finishReason",
            "baseName": "finish_reason",
            "type": "ChatCompletionResponseChoicesInnerFinishReasonEnum",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "ChatCompletionsPostRequestMessagesInner",
            "format": ""
        },
        {
            "name": "delta",
            "baseName": "delta",
            "type": "ChatCompletionResponseChoicesInnerDelta",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChatCompletionResponseChoicesInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ChatCompletionResponseChoicesInnerFinishReasonEnum {
    Stop = 'stop',
    Length = 'length'
}

